--nie zauwazylem ze nie zapisalo nazw kolumn, poprawilem recznie w tabelach :(
----------------------------------------------------------------------------
--DEPARTMENTS
CREATE TABLE DEPARTMENTS 
(
  DEPARTMENT_ID NUMBER(*, 0) NOT NULL 
, COLUMN1 VARCHAR2(120 BYTE) 
, COLUMN2 NUMBER(*, 0) 
, COLUMN3 NUMBER(*, 0) 
, CONSTRAINT DEPARTMENTS_PK PRIMARY KEY 
  (
    DEPARTMENT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX DEPARTMENTS_PK ON DEPARTMENTS (DEPARTMENT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

----------------------------------------------------------------------------
--LOCATIONS
CREATE TABLE LOCATION 
(
  LOCATION_ID NUMBER(*, 0) NOT NULL 
, COLUMN1 VARCHAR2(100 BYTE) 
, COLUMN2 VARCHAR2(8 BYTE) 
, COLUMN3 VARCHAR2(40 BYTE) 
, COLUMN4 VARCHAR2(80 BYTE) 
, COLUMN5 NUMBER(*, 0) 
, CONSTRAINT LOCATION_PK PRIMARY KEY 
  (
    LOCATION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LOCATION_PK ON LOCATION (LOCATION_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


--------------------------------------------------------------------------
--COUNTRIES
CREATE TABLE COUNTRIES 
(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 VARCHAR2(60 BYTE) 
, COLUMN3 NUMBER(*, 0) 
, CONSTRAINT COUNTRIES_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COUNTRIES_PK ON COUNTRIES (COLUMN1 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


------------------------------------------------------------------------
--REGIONS
CREATE TABLE REGIONS 
(
  REGION_ID NUMBER(*, 0) NOT NULL 
, REGION_NAME VARCHAR2(120 BYTE) 
, CONSTRAINT REGIONS_PK PRIMARY KEY 
  (
    REGION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REGIONS_PK ON REGIONS (REGION_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


---------------------------------------------------------------------
--EMPLOYEES
CREATE TABLE EMPLOYEES 
(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 VARCHAR2(60 BYTE) 
, COLUMN3 VARCHAR2(120 BYTE) 
, COLUMN4 VARCHAR2(180 BYTE) 
, COLUMN5 VARCHAR2(40 BYTE) 
, COLUMN6 DATE 
, COLUMN7 NUMBER(*, 0) 
, COLUMN8 FLOAT(126) 
, COLUMN9 FLOAT(126) 
, COLUMN10 NUMBER(*, 0) 
, COLUMN11 NUMBER(*, 0) 
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLOYEES_PK ON EMPLOYEES (COLUMN1 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( CREATE TABLE JOBS 
(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 VARCHAR2(80 BYTE) 
, COLUMN3 FLOAT(126) 
, COLUMN4 FLOAT(126) 
, CONSTRAINT JOBS_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX JOBS_PK ON JOBS (COLUMN1 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

  BUFFER_POOL DEFAULT CREATE TABLE JOBS 
(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 VARCHAR2(80 BYTE) 
, COLUMN3 FLOAT(126) 
, COLUMN4 FLOAT(126) 
, CONSTRAINT JOBS_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX JOBS_PK ON JOBS (COLUMN1 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

) 
NOCOMPRESS 
NOPARALLEL;


-------------------------------------------------------------------
--JOB_HISTORY
CREATE TABLE JOB_HISTORY CREATE TABLE JOBS 
(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 VARCHAR2(80 BYTE) 
, COLUMN3 FLOAT(126) 
, COLUMN4 FLOAT(126) 
, CONSTRAINT JOBS_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX JOBS_PK ON JOBS (COLUMN1 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 DATE NOT NULL 
, COLUMN3 DATE 
, COLUMN4 NUMBER(*, 0) 
, COLUMN5 NUMBER(*, 0) 
, CONSTRAINT JOB_HISTORY_PK PRIMARY KEY 
  (
    COLUMN1 
  , COLUMN2 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX JOB_HISTORY_PK ON JOB_HISTORY (COLUMN1 ASC, COLUMN2 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


-----------------------------------------------------------------
--JOBS
CREATE TABLE JOBS 
(
  COLUMN1 NUMBER(*, 0) NOT NULL 
, COLUMN2 VARCHAR2(80 BYTE) 
, COLUMN3 FLOAT(126) 
, COLUMN4 FLOAT(126) 
, CONSTRAINT JOBS_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX JOBS_PK ON JOBS (COLUMN1 ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


------------------------------------------------------------------------------
--FOREIGN KEYS Z JUZ PRAWIDLOWYMI NAZWAMI KOLUMN
ALTER TABLE COUNTRIES
ADD CONSTRAINT COUNTRIES_FK1 FOREIGN KEY
(
  REGION_ID 
)
REFERENCES REGIONS
(
  REGION_ID 
)
ENABLE;

alter table "MORAWSKI"."LOCATION" add constraint LOCATIONS_FK1 foreign key("COUNTRY_ID") references "COUNTRIES"("COUNTRY_ID")

--tu sie zorientowalem ze jest location zamiast locations, poprawione

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPARTMENTS_FK1 FOREIGN KEY
(
  LOCATION_ID 
)
REFERENCES LOCATIONS
(
  LOCATION_ID 
)
ENABLE;

alter table "MORAWSKI"."DEPARTMENTS" add constraint DEPARTMENTS_FK2 foreign key("MANAGER_ID") references "EMPLOYEES"("EMPLOYEE_ID")


alter table "MORAWSKI"."JOB_HISTORY" add constraint JOB_HISTORY_FK1 foreign key("JOB_ID") references "JOBS"("JOB_ID")

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JOB_HISTORY_FK2 FOREIGN KEY
(
  DEPARTMENT_ID 
)
REFERENCES DEPARTMENTS
(
  DEPARTMENT_ID 
)
ENABLE;


ALTER TABLE JOB_HISTORY
ADD CONSTRAINT JOB_HISTORY_FK3 FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

--SELF_FK
alter table "MORAWSKI"."EMPLOYEES" add constraint EMPLOYEES_SELF_FK foreign key("MANAGER_ID") references "EMPLOYEES"("EMPLOYEE_ID")

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_FK1 FOREIGN KEY
(
  JOB_ID 
)
REFERENCES JOBS
(
  JOB_ID 
)
ENABLE;

ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_FK2 FOREIGN KEY
(
  DEPARTMENT_ID 
)
REFERENCES DEPARTMENTS
(
  DEPARTMENT_ID 
)
ENABLE;

--------------------------------------------------------------
--check
ALTER TABLE JOBS
ADD CONSTRAINT JOB_CHECK1 CHECK 
((max_salary-min_salary) >= 2000)
ENABLE;