--View 1--
CREATE VIEW "VIEW1" AS
SELECT CONCAT(CONCAT(EMPLOYEES.LAST_NAME, ' '), EMPLOYEES.SALARY) AS Wynagrodzenie FROM EMPLOYEES 
WHERE ((EMPLOYEES.DEPARTMENT_ID=20) OR (EMPLOYEES.DEPARTMENT_ID=50)) AND (EMPLOYEES.SALARY > 2000 AND EMPLOYEES.SALARY < 7000)
ORDER BY EMPLOYEES.LAST_NAME;

--VIEW 2--
CREATE OR REPLACE FUNCTION VIEW2
( 
@columnName IN varchar(80)
)
RETURNS TABLE
AS
RETURN
(
    SELECT EMPLOYEES.HIRE_DATE, EMPLOYEES.LAST_NAME, 
    CASE @ColumnName
        WHEN 'EMPLOYEE_ID' THEN EMPLOYEE_ID
        WHEN 'FIRST_NAME' THEN FIRST_NAME
        WHEN 'EMAIL' THEN EMAIL
        WHEN 'PHONE_NUMBER' THEN PHONE_NUMBER
        WHEN 'JOB_ID' THEN JOB_ID
        WHEN 'SALARY' THEN SALARY
        WHEN 'COMMISSION_PCT' THEN COMMISSION_PCT
        WHEN 'MANAGER_ID' THEN MANAGER_ID
        WHEN 'DEPARTMENT_ID' THEN DEPARTMENT_ID
    END AS USER_COLUMN
    FROM EMPLOYEES
    WHERE EMPLOYEES.MANAGER_ID IS NOT NULL AND YEAR(HIRE_DATE)=2005
    ORDER BY USER_COLUMN
)
GO



--VIEW 4--
CREATE VIEW "VIEW4" AS
SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, ROUND(MONTHS_BETWEEN(CURRENT_DATE,HIRE_DATE)) AS "MONTHS",
CASE
WHEN ROUND(MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE)) < 149 THEN SALARY*0.10
WHEN ROUND(MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE)) BETWEEN 150 AND 200 THEN SALARY*0.20
WHEN ROUND(MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE)) > 200 THEN SALARY*0.30
ELSE 0 
END
AS EXTRA
FROM EMPLOYEES
ORDER BY MONTHS

--VIEW 5--
 CREATE VIEW VIEW5 AS
 SELECT SUMA, SREDNIA FROM
 (
    SELECT ROUND(SUM(EMPLOYEES.SALARY)) AS SUMA, ROUND(AVG(EMPLOYEES.SALARY)) AS SREDNIA, ROUND(MIN(SALARY)) AS MINIMUM, EMPLOYEES.DEPARTMENT_ID
    FROM EMPLOYEES
    GROUP BY EMPLOYEES.DEPARTMENT_ID
)
WHERE MINIMUM>5000;

--VIEW 6--
SELECT EMPLOYEES.LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.JOB_ID
FROM EMPLOYEES
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
INNER JOIN LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
WHERE LOCATIONS.CITY='Toronto';

--VIEW 7--
SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN
(
    SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME='Jennifer'
);


--VIEW 8--
SELECT DEPARTMENTS.* FROM DEPARTMENTS 
INNER JOIN EMPLOYEES ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE DEPARTMENTS.DEPARTMENT_ID NOT IN (
SELECT DEPARTMENTS.DEPARTMENT_ID FROM EMPLOYEES
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
)

